#!/usr/bin/env python3
"""
Per-workspace schedule customization (v2.14.10+).

Stores per-task cron schedules in `_hq/data/entities.json` under
`workspace.schedule_config`. Each scheduled-task fire reads this config when
registering or refreshing tasks; if a task isn't in the config, the built-in
default is used.

Operator-driven design: defaults ship sensible for most CEOs; the user (or
the operator running on their behalf) tunes them later via the
`change-schedule` skill or the bridge.

DATA SHAPE
==========

```json
{
  "workspace": {
    "schedule_config": {
      "cr-upcoming-meetings": {
        "cron": "30 6 * * 1-5",
        "label": "6:30 AM weekdays",
        "enabled": true
      },
      "cr-inbox": {"cron": "15 7 * * 1-5", "label": "7:15 AM weekdays", "enabled": true},
      ...
    }
  }
}
```

If `schedule_config` is absent, all tasks use built-in defaults. If a specific
task is missing from the config, that one task uses its default. If `enabled`
is false, that task is skipped at registration time.

The `label` field is a human-readable cron summary (e.g., "6:30 AM weekdays").
Generated by `cron_to_english()`. Stored alongside the cron so the change-
schedule skill can show the user what they have without re-deriving.

CRON FORMAT (5-field, LOCAL time per Cowork)
=============================================

  minute hour day_of_month month day_of_week

  * = any
  N = exact value
  N-M = range
  N,M,K = list
  */N = step

Common patterns:
  "0 7 * * 1-5"      → 7 AM weekdays
  "30 8 * * 1-5"     → 8:30 AM weekdays
  "0 7,15 * * 1-5"   → 7 AM and 3 PM weekdays
  "0 9 * * 1"        → 9 AM Mondays
  "0 9 * * *"        → 9 AM daily

DEFAULTS
========

Built-in defaults for every Command Room scheduled task. These match the
shipped cron expressions in `enable-command-room-schedules` Phase 3.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional


DEFAULT_SCHEDULES: dict[str, dict] = {
    # v2.14.27+ — bare taskIds (no cr- prefix) so Cowork's sidebar title formatting renders cleanly.
    # v3.12.0 — `inbox` shifted from 7:00 to 7:15 so it no longer collides with `morning-brief`
    # at 7:00 AM. Pre-v3.12.0 both tasks shared the 7 AM slot; the comment in this file used to
    # tell the operator to fix it manually via change-schedule. Now the default is correct
    # out of the box. Operators who already shifted inbox (or set any custom cron) keep their
    # workspace value — entities.json workspace.schedule_config overrides DEFAULT_SCHEDULES.
    "morning-brief": {
        "cron": "0 7 * * 1-5",
        "label": "7 AM weekdays",
        "enabled": True,
    },
    # `upcoming-meetings` is GONE from the default set (BRIEFMERGE, M's ruling
    # 2026-08-08 — merge the chat into the morning-brief fire; fewer chats is
    # the point). Same removal shape LIFECYCLE1 used for `pulse` and CTS1 used
    # for `commitments`: the row leaves DEFAULT_SCHEDULES so nothing offers or
    # registers it again, the DISPLAY_NAMES row stays for legacy renders, the
    # receipt vocabulary stays parseable forever, and an existing registration
    # is retired through the RETIRED_TASKS proposal below — never silently.
    # The prep generation it carried is now the morning brief's FIRST leg
    # (`shared/scripts/prep_leg.py`); the on-demand ask it answered is
    # `call-prep`, untouched.
    "inbox": {
        "cron": "15 7 * * 1-5",
        "label": "7:15 AM weekdays",
        "enabled": True,
    },
    # CTS1 (2026-07, §10.3 RULED: fresh taskIds) — the daily Commitments chat
    # split into TWO surfaces. `commitments` is REMOVED from the default set
    # (row disabled on migration per the enable-command-room-schedules Phase 1
    # legacy table — the v2.14.27 pattern; Cowork derives the sidebar title
    # FROM the taskId, so a re-scope would have left it saying "Commitments"
    # forever). Its DISPLAY_NAMES row stays for legacy renders. Neither new
    # task is first-install (same later-add posture the old `commitments`
    # had — a fresh workspace's open set hasn't accumulated).
    "waiting-on": {
        # Inherits the old commitments slot — the accountability chat is the
        # direct successor of the daily fire M's day was already built around.
        "cron": "30 8 * * 1-5",
        "label": "8:30 AM weekdays",
        "enabled": True,
    },
    "my-plate": {
        # 15 minutes after waiting-on, so its rows read the substrate the
        # waiting-on fire's CRU pre-scans (2.5/2.6/2.7) just reconciled —
        # My Plate itself is a pure substrate read (no connector pre-scans).
        # Tunable via change-schedule like any chat. (It used to be anchored
        # ahead of the 9:00 Pulse chat, which LIFECYCLE1 retired; the time is
        # kept so no existing customer's morning moves under them.)
        "cron": "45 8 * * 1-5",
        "label": "8:45 AM weekdays",
        "enabled": True,
    },
    # `pulse` is GONE from the default set (LIFECYCLE1, M's ruling 2026-08-02 —
    # eliminate the chat, fold its real jobs). Same removal shape CTS1 used for
    # `commitments`: the row leaves DEFAULT_SCHEDULES so nothing offers or
    # registers it again, the DISPLAY_NAMES row stays for legacy renders, the
    # receipt vocabulary stays parseable forever, and existing registrations
    # are retired through the RETIRED_TASKS proposal below — never silently.
    # The lifecycle work it carried is `maintenance_dispatcher`'s `lifecycle`
    # job; the dormancy question it asked is `stalled projects`.
    #
    # `past-meetings` is GONE from the default set (EOD2, M's Decision 4
    # 2026-08-16 — the 5 PM chat became the day's CLOSE in EOD1 and the id
    # kept saying "meetings"). This is a RENAME, not an elimination, and that
    # makes it the third shape of retirement this registry carries:
    #
    #   * `pulse` / `upcoming-meetings` — ELIMINATED. Their orchestrator files
    #     are retirement stubs; a still-registered task explains itself and
    #     stops.
    #   * `past-meetings` — RENAMED. Its `RETIRED_TASKS` row carries
    #     `renamed_to: "end-of-day"`, and BOTH ids map to the SAME orchestrator
    #     file, so a workspace that never takes the offer keeps a fully working
    #     evening chat FOREVER. Nothing here is a stub and nothing degrades.
    #
    # Everything the other two retirements get, this gets too: the row leaves
    # DEFAULT_SCHEDULES so nothing offers or registers it again, the
    # DISPLAY_NAMES row stays forever, the receipt vocabulary stays parseable
    # (the fire still writes its `pack_run` under `past-meetings` —
    # `end_of_day.TASK_ID`, deliberately unchanged, so pre- and post-rename
    # history is ONE continuous series), and an existing registration is
    # retired through the RETIRED_TASKS proposal below — never silently.
    "end-of-day": {
        # EOD2 — the day's close. Inherits `past-meetings`' slot and its
        # first-install membership: Decision 1's hour, unchanged, so no
        # customer's evening moves under them and the fresh-install chat
        # count stays 4.
        "cron": "0 17 * * 1-5",
        "label": "5 PM weekdays",  # == cron_to_english(cron); lockstep-pinned
        "enabled": True,
    },
    # v3.11.0 — Friday Wrap: weekly recap via weekly-recap skill. First
    # weekly-rhythm scheduled task; all prior tasks are daily.
    #
    # Phase 3 / R4 (2026-07): default moved 16:00 -> 13:00 Fridays for NEW
    # installs only. Live evidence: the 4 PM Friday slot was routinely missed
    # (laptop closed for the weekend) and Cowork fired the wrap on Sunday —
    # a >24h-late weekly recap, the exact case the R4 degrade tier suppresses.
    # 1 PM Fridays is reliably inside working hours. EXISTING registrations
    # are untouched: registration never re-anchors a live task's cron, and
    # any user-customized cron (a schedule_config override) always wins. An
    # existing install moves only when the chronic-late proposal
    # (late_fire.detect_chronic_lateness -> cleanup Monday note) offers it
    # and the user accepts via change-schedule.
    "friday-wrap": {
        "cron": "0 13 * * 5",
        "label": "1 PM Fridays",
        "enabled": True,
    },
    # MAINT1 (2026-07) — Maintenance: THE single silent background task. The
    # five silent tasks (cleanup / reconcile-sent / monthly-report /
    # weekly-insights / session-sweep) now run as JOBS inside this one task,
    # dispatched by `shared/scripts/maintenance_dispatcher.py` (a job is due
    # iff its last receipt is older than its own nominal-cron slot — code,
    # never LLM-judged). One taskId = one Run Now grant, ever: future silent
    # jobs land inside the already-authorized task instead of creating a new
    # fleet-wide never_authorized risk per release.
    #
    # Slots preserved from reconcile-sent's SPEC-2.4 cadence: the 6:45 anchor
    # stays BEFORE the 7:00 morning brief (load-bearing — the brief reads an
    # already-reconciled substrate, Bug #98-v3), and 17:45 lands after
    # past-meetings (17:00) and after relationship-moves on Sundays (17:00).
    # Daily (not weekday-only) so Sunday work (cleanup, insights) has a slot
    # and the Saturday sweep runs; a fire with nothing due is a fast no-op.
    "maintenance": {
        "cron": "45 6,12,17 * * *",
        "label": "6:45 AM, 12:45 PM, and 5:45 PM daily",
        "enabled": True,
    },
    # REL1 — Relationship Moves: weekly proactive outreach action pack. Fires
    # 5 PM Sundays (output waits Monday AM, an hour before the 6 PM cleanup).
    # NOT first-install — needs accumulated substrate for dormancy baselines, so
    # it registers via change-schedule / Phase 6 add / command-room-update-bridge,
    # same later-add posture as commitments.
    "relationship-moves": {
        "cron": "0 17 * * 0",
        "label": "5 PM Sundays",
        "enabled": True,
    },
    # `commitment-triage` is GONE from the default set (TASKRET1, M's ruling
    # 2026-08-17) — the first of the THREE READINESS retirements this registry
    # now carries. The mechanics of the removal are LIFECYCLE1's, unchanged:
    # the row leaves DEFAULT_SCHEDULES so nothing offers or registers it again,
    # the DISPLAY_NAMES row stays forever, and the receipt vocabulary stays
    # parseable. What is NEW is the removal PATH — a readiness retirement is
    # applied by the update bridge instead of proposed, because M refused
    # per-task proposals for this class. The reasoning lives in one place: the
    # `retirement_class` block below RETIRED_TASKS.
    #
    # The ON-DEMAND surface is untouched. `triage my commitments` still runs
    # the identical full-open-set pass (`skills/commitment-triage/SKILL.md`);
    # only the weekly Friday 3 PM fire is gone.
    # LB1 R3 — Staff Meeting: the Living Brain's weekly review chat. The
    # COMPLETE pending-proposal queue (paginated, exempt from daily dedup) +
    # the change feed since the last staff meeting + "This week's moves"
    # (the relationship-moves machinery rendered as a section — R4). Fires
    # Monday 9 AM (Friday already carries wrap 13:00 + triage 15:00); the
    # Sunday-evening maintenance jobs (deal-signals among them) have just
    # refilled the queue. Weekly by DEFAULT, tunable via change-schedule
    # like any chat — a second weekly slot is a user choice, never a
    # default. NOT first-install — propose-only later-add posture, same as
    # relationship-moves / commitment-triage: registers via change-schedule
    # / registration Phase 6 add / update-bridge proposal, NEVER silently
    # auto-registered.
    # FB-20 (M's ruling 2026-07-16): Mon-only → Mon/Wed/Fri. The morning brief
    # became read-only, so the staff meeting is the SOLE adjudication surface —
    # a once-a-week confirm queue is now the only door, and a week is too long
    # to hold a deal signal behind. "Run staff meeting more often instead" is
    # the other half of de-carding the brief; this is that half.
    # NEW INSTALLS ONLY. An existing registration keeps whatever cron it has:
    # the update bridge PROPOSES this change (`staff_meeting_cadence_mwf_v1`)
    # and never rewrites a customer's schedule silently.
    "staff-meeting": {
        "cron": "0 9 * * 1,3,5",
        "label": "9 AM Mon, Wed, Fri",  # == cron_to_english(cron); see the
                                        # lockstep guard in the FB-20 test
        "enabled": True,
    },
    # `pipeline-digest` is GONE from the default set (TASKRET1, M's ruling
    # 2026-08-17) — the second READINESS retirement. It is the only one of the
    # three that had an AUTOMATED offer path, so its removal is two edits, not
    # one: this row, and the `pipeline-digest` entry in
    # `schedule_proposals.PROPOSAL_THRESHOLDS` (deleted there, pinned absent by
    # test, so a re-add is a deliberate act rather than a merge artifact).
    # The on-demand pipeline report is untouched (`skills/pipeline-tracker/`);
    # only the weekly Tuesday 8 AM fire is gone.
    #
    # `balance` is GONE from the default set (TASKRET1, same ruling) — the
    # third READINESS retirement, and the one whose gate was already written
    # down: BAL1 shipped it needing accumulated substrate AND a declared
    # personal calendar, and shipping a chat behind a gate most workspaces
    # cannot clear is exactly what this retirement class exists to undo. The
    # on-demand surface is untouched (`balance check` / `skills/balance/`);
    # only the weekly Sunday 8 AM fire is gone.
    # cr-refresh-workspace-map removed v2.14.25. The five silent-task rows
    # (cleanup 18:00 Sun / reconcile-sent 6:45,12:45,17:45 weekdays /
    # monthly-report 7:00 on the 1st / weekly-insights 19:00 Sun /
    # session-sweep 22:00 daily) were superseded by the single `maintenance`
    # task in MAINT1 (2026-07) — their cadences live on as job-level nominal
    # crons in maintenance_dispatcher.MAINTENANCE_JOBS, and the old taskIds
    # are disabled on migration per SUPERSEDED_BY below.
}


# M1 (2026-05-23) — the tasks registered on a fresh-install workspace.
# Detection: workspace_config.json missing OR has empty registered_taskIds.
# Pre-M1 the set was 4 (morning-brief / upcoming-meetings / past-meetings /
# friday-wrap), with inbox deferred to a later Zapier-integration session.
# M1 brings inbox forward — the Chat 2 substantive education + the Phase 4
# Run Now ritual establish them in one onboarding pass.
# BRIEFMERGE (2026-08-08) drops `upcoming-meetings`: its prep generation is now
# the morning brief's first leg, so the fresh-install chat set is 4 (the fifth
# entry, `maintenance`, is the silent background task).
# EOD2 (2026-08-16) swaps `past-meetings` for `end-of-day` — a RENAME, so the
# successor inherits the slot rather than adding one. The fresh-install chat
# count is still 4.
# The remaining defaults (waiting-on, my-plate — CTS1 split the old
# commitments chat into the two) stay deferred — both benefit from
# accumulated workspace signal before they fire well.
FIRST_INSTALL_TASK_IDS: frozenset[str] = frozenset({
    "morning-brief",
    "end-of-day",    # EOD2 — inherits `past-meetings`' first-install slot (rename, not an addition)
    "inbox",         # M1 — promoted into first-install set; surfaced to customer as `inbox-triage`
    "friday-wrap",   # v3.11.0 weekly rhythm; surfaced to customer as `weekly-recap`
    "maintenance",   # MAINT1 — THE silent background task; the five pre-MAINT1 silent taskIds (cleanup / reconcile-sent / monthly-report / weekly-insights / session-sweep) run as its jobs and are disabled on migration (SUPERSEDED_BY).
})


# -----------------------------------------------------------------------------
# SILENT_TASKS registry (Phase 3 / SPEC-2.3, 2026-07)
# -----------------------------------------------------------------------------
# Data-driven registration for the silent (non-chat) background tasks. This
# dict is the single source of truth the three registration paths loop over:
#   1. enable-command-room-schedules Step 1.D (registration loop),
#   2. enable-command-room-schedules Phase 5.9 (unconditional assertion loop),
#   3. command-room-update-bridge Phase 4.7 (post-update back-fill loop).
# Adding a new silent task here registers it via all three paths with zero
# prose edits — the pre-registry design needed a new SKILL.md step (1.E/1.F/
# 1.G...) plus a new Phase 5.9 bullet plus a bridge edit for every task, and
# each of those was a place to forget one (Bug #82 was exactly that miss).
#
# Cron/label/enabled come from DEFAULT_SCHEDULES (derive, don't duplicate) —
# an entry here without a DEFAULT_SCHEDULES row is a registration-time error.
#
# `reason` is the one-line customer-facing explanation the W2 install ritual
# prints next to each silent task, because silent tasks never clear Cowork's
# first-fire permission gate on their own: the customer has to Run Now each
# one once, and they'll only do that if they know why it exists.
#
# `prompt` is the registered task prompt with a `{BASENAME}` placeholder for
# the customer-confirmed workspace folder basename (compose via
# compose_silent_task_prompt). These are skill-invoking prompts, not
# bootloaders — the skill body is read from the installed plugin at fire
# time, so plugin upgrades propagate without re-registration.
SILENT_TASKS: dict[str, dict] = {
    # MAINT1 (2026-07) — the registry's ONE entry. The five pre-MAINT1 silent
    # tasks run as jobs inside this task; their execution contracts live in
    # their own SKILL.md files, and the dispatcher (maintenance_dispatcher.py)
    # decides due-ness in code. All three registration paths (Step 1.D loop,
    # Phase 5.9 assertion, bridge Phase 4.7 loop) keep working UNCHANGED —
    # they iterate this registry, which now registers/asserts one task.
    "maintenance": {
        "description": (
            "Background maintenance — reconciles sent mail, sweeps sessions, "
            "runs weekly cleanup + insights and the monthly report (silent)"
        ),
        "reason": (
            "handles all the background upkeep in one place — closing "
            "commitments you finished by email, catching unlogged decisions, "
            "the weekly tidy and the monthly report"
        ),
        "notify": False,
        "prompt": (
            "# Command Room — maintenance (silent background dispatcher)\n\n"
            "Run the Command Room maintenance pass for the workspace whose folder "
            "basename is {BASENAME}. Resolve the workspace per CONTRACT.md Rule 22 "
            "(find _hq/ under the mount matching that basename), resolve the plugin "
            "root, then:\n\n"
            "0. MOUNT-FRESHNESS PREFLIGHT (SPEC SYNC1 A4 — do this FIRST, before "
            "asking what is due): run `python3 -c \"import sys; "
            "sys.path.insert(0,'shared/scripts'); import json, substrate_health as h; "
            "print(json.dumps(h.preflight_freshness('<workspace_root>')))\"` from the "
            "plugin root. If it returns ok=false the substrate view is stale (a stale "
            "sandbox mount or mid-sync) — it has already written the .mount_stale "
            "sidecar and rendered the alert via alarm_artifacts.write_alert (NEVER "
            "hand-author an alert). EXIT IMMEDIATELY: run NO jobs, write NO receipts. "
            "Every job stays due and auto re-fires next slot, and reconcile_forward "
            "self-heals any quarantined batches on the next healthy fire — zero manual "
            "recovery. Only when ok=true proceed to step 1.\n"
            "1. Ask the dispatcher what is due — NEVER judge due-ness yourself: run "
            "`python3 shared/scripts/maintenance_dispatcher.py <workspace_root>` from "
            "the plugin root and hold its JSON plan. The `due` list is ordered — that "
            "order is the contract (reconcile-sent first at 6:45, before the 7:00 "
            "morning brief; weekly-insights after cleanup). A due job that carries a "
            "`periods` list is PARTITIONED — obey step 2b for it. If nothing is due, "
            "append the run receipt via maintenance_dispatcher.maintenance_receipt "
            "(empty lists, plus any skipped_disabled from the plan) and exit "
            "silently.\n"
            "2. Execute each due job's skill END-TO-END, one at a time in plan order, "
            "never in parallel: reconcile-sent -> skills/reconcile-sent/SKILL.md; "
            "session-sweep -> skills/session-sweep/SKILL.md; cleanup -> "
            "skills/cleanup/SKILL.md (every phase); weekly-insights -> "
            "skills/insight-generator/SKILL.md; identity-reconcile -> run "
            "`python3 shared/scripts/identity_reconcile.py --workspace "
            "<workspace_root> --apply` from the plugin root (PID1 — the flag "
            "matters: without --apply it dry-runs, writes no receipt, and "
            "stays due forever; auto-adds are narrated + batch-undoable, "
            "links/merges are propose-only, its identity_reconcile_run "
            "receipt is written by the script itself); lifecycle -> run "
            "`python3 shared/scripts/lifecycle_pass.py --workspace "
            "<workspace_root> --apply` from the plugin root (LIFECYCLE1 — the "
            "flag matters exactly as it does for identity-reconcile: without "
            "--apply it dry-runs, writes no receipt, and stays due forever. "
            "Dormancy questions ride the confirm rail as ON-DEMAND rows — they "
            "surface when the CEO says `stalled projects`, never on a "
            "scheduled surface — and the dormant->archived leg goes through "
            "the canonical archive path; its lifecycle_run receipt is written "
            "by the script itself); review-expiry -> run "
            "`python3 shared/scripts/commitment_backlog_sweep.py "
            "review-expiry --workspace <workspace_root> --apply` from the "
            "plugin root (REVSCHED1 — the flag matters exactly as it does "
            "for identity-reconcile and lifecycle: without --apply it "
            "dry-runs, writes no receipt, and stays due forever. It lapses "
            "unconfirmed captures nobody answered inside the review window, "
            "reversibly, in ONE undoable batch; it NEVER touches the "
            "confirmed tier and it takes no row list. Its pack_run receipt "
            "is written by the script itself, on an empty plan too. Say "
            "NOTHING to the CEO here: when its `receipt_line` is non-empty, "
            "the next staff meeting / end-of-day reads that ONE line out "
            "verbatim; an empty plan is a silent no-op); monthly-report -> for EACH "
            "period in the job's `periods` list (step 2b), the operator report per "
            "skills/operator-report/SKILL.md then the value receipt per "
            "skills/value-receipt/SKILL.md over that period's own calendar month "
            "(quarter boundary adds the quarterly roll-up); monthly-scorecard "
            "(OPT-IN, SPEC OUT7 — present only when the "
            "workspace turned it on) -> for EACH period in its `periods` list, "
            "assemble THAT month's KPIs-vs-targets "
            "readings the way board-pack §2 does (QuickBooks + KPI-target decision "
            "events + the prior pack; every reading substrate-derived — a KPI with "
            "no substrate value passes current=None, NEVER an estimated or invented "
            "number), then render the scorecard via "
            "shared/scripts/scorecard.py build_scorecard(period='month', "
            "data_through=<latest substrate date>) -> make_brief(brief_kind='kpi_scorecard', "
            "...); write its pack_run receipt via receipts.log_receipt(workspace_root, "
            "'monthly-scorecard', receipt_type='pack_run', fired_via='scheduled') so it "
            "self-limits to monthly.\n"
            "2b. PARTITIONED JOBS — one deliverable per missed period, never one "
            "standing in for several (SPEC CATCHUP1 F-3/F-4). A due job carrying a "
            "`periods` list has one entry per nominal period that went unserved, "
            "ALREADY OLDEST FIRST. Iterate it in that order and produce a SEPARATE "
            "deliverable for each entry, each computed over and labelled with ITS OWN "
            "period — a machine closed across the 1st means the skipped month is owed "
            "as well as the newest one, and 'the previous full calendar month' "
            "measured from today would silently drop it. Windows are half-open "
            "[first-of-period, first-of-next-period). Never merge two periods into "
            "one artifact, never relabel an older period as the newest, and never "
            "skip an entry because a newer one covers 'roughly' the same ground. If "
            "`periods_capped` is true, more periods were missed than the dispatcher "
            "enumerates in one fire and the OLDEST were dropped — the job's receipt "
            "self-limits it to monthly from here, so say nothing to the CEO but note "
            "the drop in jobs_failed reasoning rather than reporting a clean sweep. "
            "Write the job's receipt ONCE, after the last period's deliverable "
            "lands; a receipt written after the first period would leave the rest "
            "looking served.\n"
            "3. A job COMPLETED only when its own receipt validator confirms its own "
            "substrate receipt (validate_reconcile_ran / validate_sweep_ran / the "
            "cleanup, insights, and report receipts per each SKILL.md). Never report "
            "a job done without its receipt — an unreceipted job stays due and "
            "self-heals at the next fire; list it in jobs_failed instead.\n"
            "4. Finish with ONE maintenance_dispatcher.maintenance_receipt call "
            "(jobs_due / jobs_completed / jobs_failed / skipped_disabled from what "
            "actually happened) and confirm it landed via validate_maintenance_ran.\n\n"
            "Each job keeps its own skill's surfacing rules — stay silent unless a "
            "job's contract says something needs the CEO eyes (a closure line, the "
            "Monday note, the monthly report links). This is silent maintenance, NOT "
            "a chat-widget."
        ),
    },
}


# MAINT1 migration data (D5) — the registration paths read this map, not
# prose: when a registry task is registered (Step 1.D / Phase 5.9 / bridge
# Phase 4.7), any taskId listed under it that is still registered+enabled is
# DISABLED via update_scheduled_task(enabled: false). Never deleted (no
# delete API exists; disable is the only removal) and idempotent — disabling
# an already-disabled task is a no-op, and re-runs converge on the same end
# state: the five old ids off, exactly one `maintenance` task on.
SUPERSEDED_BY: dict[str, list[str]] = {
    "maintenance": [
        "cleanup",
        "reconcile-sent",
        "monthly-report",
        "weekly-insights",
        "session-sweep",
    ],
}


# -----------------------------------------------------------------------------
# RETIRED_TASKS registry (SPEC LIFECYCLE1, 2026-08-02)
# -----------------------------------------------------------------------------
# A task that has been ELIMINATED, not merely deferred. The distinction the
# whole retirement turns on:
#
#   * a LATER-ADD task (`waiting-on`, `staff-meeting`, `balance`…) is absent
#     because the workspace has not added it YET. system-health says nothing,
#     change-schedule offers it, the bridge may propose it.
#   * a RETIRED task is absent because it is GONE. Nothing offers it, nothing
#     registers it, system-health treats its absence as normal and NEVER flags
#     it — and a workspace that still has it registered is offered ONE
#     proposal to switch it off. Never silently: disabling a task the customer
#     can see in their Scheduled list, without saying so, is the same posture
#     violation as registering one without asking.
#
# Membership is THIS registry, never a name check in prose — the same lesson
# SILENT_TASKS learned (Bug #82: every hand-written per-task block is a place
# to forget one). `replacement` is customer-facing plain English naming where
# the work went, so the retirement line never reads as a feature being taken
# away.
#
# TWO KINDS OF RETIREMENT (EOD2, 2026-08-16). An entry carrying `renamed_to`
# is a RENAME: the task was not eliminated, it was re-identified. The
# difference is not cosmetic and it changes three behaviours:
#
#   1. The successor is a REAL registry task (`end-of-day` is in
#      DEFAULT_SCHEDULES and FIRST_INSTALL_TASK_IDS), where an eliminated
#      task's work went to a DIFFERENT existing surface.
#   2. Both ids resolve to the SAME orchestrator file, so a still-registered
#      predecessor keeps firing the real pack forever — it never degrades to
#      a stub, and system-health never has anything to say about it.
#   3. The successor must NOT auto-register on a workspace whose predecessor
#      is still registered — that would silently hand the customer TWO 5 PM
#      chats. `registration_target_set()` is the fence; the offer is the
#      only path in.
#
# THREE KINDS, AND WHY THE THIRD EXISTS (SPEC TASKRET1, M's ruling 2026-08-17).
# Read `retirement_class(task_id)`, never a name you remember. The classes are
# distinguished by what a customer's LIVE registration experiences on update:
#
#   * ELIMINATION (`pulse`, `upcoming-meetings`) — PROPOSE, NEVER SILENT. The
#     chat is gone; the customer is OFFERED `pause <name>` and nothing is
#     disabled until they take it. Correct for a chat sitting visibly in their
#     Scheduled list whose removal is a judgement call they may disagree with.
#   * RENAME (`past-meetings` → `end-of-day`) — PROPOSE, NEVER SILENT, and the
#     accept is an `add`, not a `pause`. Nothing degrades while they ignore it.
#   * READINESS (`commitment-triage`, `pipeline-digest`, `balance`) — APPLIED
#     ON UPDATE, and NARRATED. The bridge's readiness migration disables the
#     live registration itself and says so in one line of the update ack; the
#     customer is told what happened and why, not asked.
#
# The third class is deliberate, and it is not a softening of the second. The
# product shipped these three surfaces BEFORE the substrate that makes them
# say anything true existed. A surface that fires weekly with nothing honest
# to say does not merely waste a slot — it teaches the operator to ignore that
# slot, permanently, and that lesson survives the fix. M's ruling is the
# authority for acting rather than asking ("I will NOT manually pause"):
# register-then-nag is the failure mode being removed, so a per-task proposal
# would reproduce it under a new name.
#
# What keeps this honest rather than silent is `reoffer_when` — every readiness
# entry names, in the customer's own language, the condition under which the
# surface comes BACK. That is the difference between this and
# `SUPERSEDED_BY` (which is silent, and correct for background tasks the
# customer never saw): a readiness retirement is a loan, not a deletion, and
# the update ack says so. Nothing here weakens the ELIMINATION/RENAME
# contract — those two still propose, and a test pins that the two paths
# diverge on class rather than on which registry row happens to be first.
RETIRED_TASKS: dict[str, dict] = {
    "pulse": {
        "retired_in": "LIFECYCLE1",
        "reason": (
            "it fired every weekday morning to say what the morning brief and "
            "the staff meeting already say"
        ),
        "replacement": (
            "the quiet-project questions it used to raise now wait until you "
            "ask for them — say 'stalled projects' — and the housekeeping it "
            "did in the background runs weekly with everything else"
        ),
    },
    "upcoming-meetings": {
        "retired_in": "BRIEFMERGE",
        "reason": (
            "it fired half an hour before your morning brief to prep the same "
            "meetings the brief already walks you through"
        ),
        "replacement": (
            "your morning brief now preps today's meetings itself before it "
            "writes — same briefs, same folder, one chat — and anything booked "
            "after it runs is one ask away: say 'prep me for my 2pm'"
        ),
    },
    "past-meetings": {
        "retired_in": "EOD2",
        # THE RENAME MARKER. Its presence is what makes this a rename rather
        # than an elimination — read it, never a name you remember.
        "renamed_to": "end-of-day",
        # For a rename, `reason` is the clause that follows the em dash in the
        # customer line, so it says what is UNCHANGED. The hour is NOT typed
        # here: `retirement_line` derives it from the successor's own cron, so
        # moving the default can never leave this sentence quoting a time the
        # task no longer fires at.
        "reason": "same {time} close, same chat, one tap to switch",
        "replacement": (
            "Say `add end of day` and I'll register it and switch Past "
            "Meetings off in the same step; leave it and your evening chat "
            "keeps firing exactly as it does today"
        ),
    },
    # ---- READINESS retirements (SPEC TASKRET1, M's ruling 2026-08-17) -------
    # Each carries `retirement_class: "readiness"` — THE class marker, and the
    # thing every caller reads. No `renamed_to`: nothing here was
    # re-identified, so a rename-shaped line would be a lie about a chat that
    # is not coming back under another name.
    #
    # `reoffer_when` is the field this class adds, and it is CUSTOMER-FACING —
    # it is quoted verbatim into the update ack. Keep it plain English. The
    # internal build ids that actually gate each re-offer are recorded in the
    # comment above each entry, deliberately NOT in the string: a customer
    # reading "back when REVAMN1 ships" has learned nothing.
    "commitment-triage": {
        "retired_in": "TASKRET1",
        "retirement_class": "readiness",
        # Re-offer gate (internal): the review-tier backlog model sound —
        # REVAMN1 shipped + the PREC1 precision verdicts filled in.
        "reason": (
            "a weekly pass over the whole list only helps once the list is "
            "trustworthy, and the sorting that decides what belongs on it is "
            "still being built"
        ),
        "reoffer_when": (
            "the backlog sorts itself well enough that a weekly review is "
            "reading a real list"
        ),
        "replacement": (
            "Nothing is lost — say `triage my commitments` any time and the "
            "same full review runs on the spot"
        ),
    },
    "pipeline-digest": {
        "retired_in": "TASKRET1",
        "retirement_class": "readiness",
        # Re-offer gate (internal): the deal-tracking rework / PIPE1 successor.
        "reason": (
            "it reports on tracked deals every week, and deal tracking itself "
            "is being rebuilt underneath it"
        ),
        "reoffer_when": (
            "deal tracking has been rebuilt and the weekly report has "
            "something steady to read"
        ),
        "replacement": (
            "Nothing is lost — ask for the pipeline any time and you get the "
            "same report on the spot"
        ),
    },
    "balance": {
        "retired_in": "TASKRET1",
        "retirement_class": "readiness",
        # Re-offer gate (internal): accumulated personal-lane substrate AND a
        # declared `workspace.personal_calendars` — BAL1's own shipped gate,
        # which most workspaces have never been able to clear.
        "reason": (
            "it needs a connected personal calendar and months of history "
            "behind it before it can say anything true about your time, and "
            "without those it fires weekly with nothing to tell you"
        ),
        "reoffer_when": (
            "there's a personal calendar connected and enough history behind "
            "it to be honest about what has gone quiet"
        ),
        "replacement": (
            "Nothing is lost — say `balance check` any time and it runs on "
            "the spot"
        ),
    },
}

# The 6-week suppression window a retirement proposal honors, mirroring
# `schedule_proposals.REPROPOSE_SUPPRESSION_WEEKS` for the add direction: an
# offer the customer ignored is not an offer to repeat next Tuesday.
RETIRE_SUPPRESSION_WEEKS = 6


def is_retired_task(task_id: str) -> bool:
    """True when `task_id` is OUT of the live set — eliminated OR renamed.
    Class membership is the RETIRED_TASKS registry, never a hardcoded name
    list. What every caller needs from this class is the same regardless of
    which kind it is: never offer it, never register it fresh, and never
    report its absence — system-health treats it as "retired, quiet".

    Use `is_renamed_task` to tell the two kinds apart where the difference
    matters: an ELIMINATED task's orchestrator is a retirement stub and its
    work moved to another surface, while a RENAMED task's orchestrator is the
    live successor's file and the old registration keeps firing the real pack
    (EOD2)."""
    return task_id in RETIRED_TASKS


def is_renamed_task(task_id: str) -> bool:
    """True when `task_id` was RENAMED into a live successor rather than
    eliminated. Membership is the `renamed_to` field on the RETIRED_TASKS
    row — never a name list."""
    return bool((RETIRED_TASKS.get(task_id) or {}).get("renamed_to"))


# The three retirement classes. `retirement_class()` returns one of these for
# a retired id and "" for a live one — callers branch on the RETURN VALUE,
# never on a name they remember.
RETIREMENT_CLASS_ELIMINATION = "elimination"
RETIREMENT_CLASS_RENAME = "rename"
RETIREMENT_CLASS_READINESS = "readiness"


def retirement_class(task_id: str) -> str:
    """Which KIND of retirement `task_id` is — the one dispatch point.

    Returns `""` for a task that is not retired, else one of
    `RETIREMENT_CLASS_ELIMINATION` / `_RENAME` / `_READINESS`.

    Derivation order matters. An explicit `retirement_class` field on the row
    WINS, because the readiness class is a deliberate posture choice that no
    other field implies. Absent that field the class is derived exactly as it
    always was — `renamed_to` present means rename, absent means elimination —
    so the pre-TASKRET1 rows keep their behaviour without being re-annotated,
    and a future row that forgets the field degrades to the SAFE class
    (elimination = propose, never silent) rather than to the acting one.

    That default direction is the whole safety property here: a typo in the
    class marker costs a customer one proposal they can ignore, never a chat
    disabled without being asked.
    """
    spec = RETIRED_TASKS.get(task_id)
    if not spec:
        return ""
    declared = (spec.get("retirement_class") or "").strip()
    if declared:
        return declared
    return (RETIREMENT_CLASS_RENAME if spec.get("renamed_to")
            else RETIREMENT_CLASS_ELIMINATION)


def is_readiness_retirement(task_id: str) -> bool:
    """True when `task_id` came out because its SUBSTRATE wasn't ready
    (SPEC TASKRET1) — the class the update bridge APPLIES rather than
    proposes. Membership is `retirement_class`, never a name list."""
    return retirement_class(task_id) == RETIREMENT_CLASS_READINESS


def readiness_retired_task_ids() -> frozenset[str]:
    """Every readiness-retired id. DERIVED from the registry so the bridge
    migration, the tests and any future surface all read one list."""
    return frozenset(t for t in RETIRED_TASKS if is_readiness_retirement(t))


def reoffer_condition(task_id: str) -> str:
    """The customer-facing condition under which a readiness-retired surface
    COMES BACK. Empty string for every other class — nothing else makes this
    promise, and inventing one would be a commitment the product hasn't made.

    This is the field that separates a readiness retirement from a silent
    `SUPERSEDED_BY` disable: the customer is told the surface is on loan, not
    deleted, and told what redeems it."""
    if not is_readiness_retirement(task_id):
        return ""
    return (RETIRED_TASKS.get(task_id) or {}).get("reoffer_when", "")


def renamed_predecessors(task_id: str) -> tuple[str, ...]:
    """The retired ids that were RENAMED INTO `task_id` — the inverse of
    `renamed_to`, derived so there is no second map to keep in step.

    A registered predecessor SERVES its successor: same orchestrator file,
    same pack, same receipt series. Callers use this to answer "is this task
    covered on this machine?" without asking the customer to re-register
    anything (`serving_task_ids` is the convenience wrapper)."""
    return tuple(sorted(
        tid for tid, spec in RETIRED_TASKS.items()
        if spec.get("renamed_to") == task_id
    ))


def schedule_task_id(task_id: str) -> str:
    """The id whose DEFAULT_SCHEDULES row governs `task_id`'s CADENCE.

    Identity for every live id, and for a retired id that was eliminated (it
    has no cadence — nothing should be asking). For a RENAMED retired id it
    is the SUCCESSOR: the predecessor left DEFAULT_SCHEDULES, but the task it
    names is still registered and still firing, on the successor's cron,
    because they are the same chat at the same hour.

    Anything that asks "when should this have fired?" must resolve through
    here. `late_fire` is the case that proved it: on the day EOD2 shipped,
    every un-renamed machine's evening fire would have looked up
    `past-meetings`, found no row, and returned tier `unknown` — lateness
    detection and the catch-up banner silently off for the whole fleet, on
    the one chat that fires last thing every weekday.
    """
    successor = (RETIRED_TASKS.get(task_id) or {}).get("renamed_to")
    if successor and successor in DEFAULT_SCHEDULES:
        return successor
    return task_id


def serving_task_ids(task_id: str) -> tuple[str, ...]:
    """`task_id` plus every registered-id that would serve it — itself first.

    The order matters for readers that take the first match: the current id
    wins, a renamed predecessor is the fallback."""
    return (task_id,) + renamed_predecessors(task_id)


def is_task_served(task_id: str, registered_ids) -> bool:
    """True when `task_id`'s work is covered by what is REGISTERED here —
    either under its own id or under a renamed predecessor's.

    This is the check that keeps a rename from reading as breakage. A
    workspace still running `past-meetings` has an evening close; saying its
    `end-of-day` chat is "missing from the schedule" would be false, and
    acting on it would register a second 5 PM chat."""
    registered = set(registered_ids or ())
    return any(tid in registered for tid in serving_task_ids(task_id))


def cron_time_phrase(expr: str) -> str:
    """The clock half of a cron's English label — "5 PM" from
    `0 17 * * 1-5`. Empty string when the expression doesn't parse or names
    more than one time.

    Exists so customer copy can quote a task's hour without typing it: a
    hand-typed hour in a retirement sentence is a second copy of the cron,
    and it goes stale the first time the default moves."""
    try:
        minute_set, hour_set, _dom, _month, _dow = parse_cron(expr)
    except CronParseError:
        return ""
    if len(hour_set) != 1 or len(minute_set) != 1:
        return ""
    return _format_time(next(iter(hour_set)), next(iter(minute_set)))


def retirement_reason(task_id: str) -> str:
    """The retired task's `reason`, with any registry placeholder resolved.

    A RENAME entry's reason carries `{time}` so the hour is read from the
    successor's own cron rather than typed twice. Callers that surface the
    reason on its own (the proposal record, telemetry) must go through here
    — handing a raw `{time}` to a customer-facing string is the failure this
    exists to prevent."""
    spec = RETIRED_TASKS.get(task_id)
    if not spec:
        return ""
    reason = spec.get("reason", "")
    successor = spec.get("renamed_to")
    if successor and "{time}" in reason:
        phrase = cron_time_phrase(
            (DEFAULT_SCHEDULES.get(successor) or {}).get("cron", "")
        ) or "same-time"
        reason = reason.replace("{time}", phrase)
    return reason


def retirement_line(task_id: str) -> str:
    """The ONE customer-facing sentence for a retired task.

    Built from the registry so the wording cannot drift between the bridge,
    change-schedule, registration and system-health. Empty string for a task
    that is not retired — callers surface nothing rather than inventing a
    line.

    THREE SHAPES, and the registry picks (EOD2, extended by TASKRET1):

      * ELIMINATED (`pulse`, `upcoming-meetings`) — the chat is gone and the
        line offers the `pause` that clears it.
      * RENAMED (`past-meetings` → `end-of-day`) — the chat is NOT gone, so a
        "your chat is retired" sentence would be a lie about a task that
        fires tonight. The line says what it is called now, quotes the hour
        FROM the successor's own cron, and offers the switch.
      * READINESS (`commitment-triage`, `pipeline-digest`, `balance`) — the
        update has ALREADY switched it off, so the line must not ask for a
        `pause` the customer no longer has to perform; offering one would be
        the product asking for a tap it already took. It states what
        happened, why, where the same work still lives on demand, and — the
        clause only this class carries — what brings the chat back.

    The readiness branch reads its optional clauses with `.get`, never
    `[...]`. This is the ONE customer-facing renderer, and it is reached from
    four places (the three stubs, change-schedule's `add` refusal, the bridge
    ack, and every `plan_readiness_retirements` entry's `line`). A row that
    forgets `replacement` or `reoffer_when` must therefore DEGRADE to a
    shorter sentence that is still true, not raise `KeyError` in front of a
    customer — the same discipline the suite applies to its own reads. A
    complete row renders byte-identically to the hardcoded form.
    """
    spec = RETIRED_TASKS.get(task_id)
    if not spec:
        return ""
    name = DISPLAY_NAMES.get(task_id, task_id)
    kind = retirement_class(task_id)
    if kind == RETIREMENT_CLASS_READINESS:
        # `retirement_reason`, not the raw field — identical output today
        # (readiness rows carry no placeholder), and the ONE place a future
        # placeholder gets resolved rather than handed to a customer raw.
        reason = (retirement_reason(task_id) or "").strip()
        replacement = (spec.get("replacement") or "").strip()
        reoffer = (spec.get("reoffer_when") or "").strip()
        line = (f"Your {name} chat is off the schedule — {reason}."
                if reason else f"Your {name} chat is off the schedule.")
        if replacement:
            line += f" {replacement}."
        if reoffer:
            line += f" It comes back when {reoffer}."
        return line
    successor = spec.get("renamed_to")
    if successor:
        new_name = DISPLAY_NAMES.get(successor, successor)
        return (f"Your {name} chat is now {new_name} — "
                f"{retirement_reason(task_id)}. {spec['replacement']}.")
    return (f"Your {name} chat is retired — {spec['reason']}. Say "
            f"`pause {name.lower()}` and I'll switch it off; {spec['replacement']}.")


def readiness_retirement_summary(task_ids) -> str:
    """The ONE line the update bridge posts after the readiness migration
    disabled something (SPEC TASKRET1 §2.4). Empty string for an empty list —
    a workspace that had none of the three hears NOTHING, which is the
    behaviour on the overwhelming majority of installs.

    Composed here rather than typed in the bridge for the reason every other
    retirement string is: the wording has to be identical wherever it appears,
    and a sentence hand-typed into a SKILL.md is a second copy that drifts on
    the first edit. The per-task `reoffer_when` clauses are what make this an
    ACK rather than a silent disable — drop them and this class becomes
    `SUPERSEDED_BY` with extra steps.

    Ids that are not readiness retirements are ignored, not rendered: this
    line promises a return, and only this class has one to promise.
    """
    ids = [t for t in (task_ids or []) if is_readiness_retirement(t)]
    if not ids:
        return ""
    names = [DISPLAY_NAMES.get(t, t) for t in ids]
    if len(names) == 1:
        listed = names[0]
    elif len(names) == 2:
        listed = f"{names[0]} and {names[1]}"
    else:
        listed = ", ".join(names[:-1]) + f" and {names[-1]}"
    noun = "chat" if len(ids) == 1 else "chats"
    head = (f"Switched off {len(ids)} scheduled {noun} that need more "
            f"groundwork first: {listed}.")
    tail = " ".join(
        f"{DISPLAY_NAMES.get(t, t)} comes back when {reoffer_condition(t)}."
        for t in ids
    )
    return f"{head} {tail}"


def is_silent_task(task_id: str) -> bool:
    """True when `task_id` is a silent (non-chat) background task. Class
    membership is the SILENT_TASKS registry — never a hardcoded name list.
    Late-fire degradation (Phase 3 R4) exempts this class; the W2 install
    ritual lists this class explicitly with reasons."""
    return task_id in SILENT_TASKS


def compose_silent_task_prompt(task_id: str, workspace_basename: str) -> str:
    """Compose the registered prompt for a silent task from the registry.

    Raises KeyError on an unknown task and ValueError on a basename that
    isn't a bare folder name — the same hard checks the bootloader
    composition applies, so a registration path can't quietly register a
    prompt with an unsubstituted or path-shaped basename.
    """
    basename = (workspace_basename or "").strip()
    if not basename or "/" in basename or "\\" in basename:
        raise ValueError(
            f"workspace_basename must be a bare folder basename, got {basename!r}"
        )
    spec = SILENT_TASKS[task_id]
    prompt = spec["prompt"].replace("{BASENAME}", basename)
    if "{BASENAME}" in prompt:
        raise ValueError(f"{task_id}: unsubstituted BASENAME placeholder after compose")
    return prompt


# Display names — taskId → user-facing name. Keep in sync with chat orchestrator
# titles. Used by change-schedule skill to render schedules in plain English.
DISPLAY_NAMES: dict[str, str] = {
    "morning-brief": "Morning Brief",
    "upcoming-meetings": "Upcoming Meetings",  # BRIEFMERGE — RETIRED taskId (out of DEFAULT_SCHEDULES; row kept forever so pre-retirement receipts and any still-registered task render with a name, never a bare id)
    "inbox": "Inbox",
    "commitments": "Commitments",  # CTS1 — retired taskId (disabled on migration; row kept for legacy renders of pre-CTS1 receipts/schedules)
    "waiting-on": "Waiting On",  # CTS1 Surface 1 — things people owe the user (the re-scoped daily; owns the unowned/unconfirmed confirm tail)
    "my-plate": "My Plate",      # CTS1 Surface 2 — things the user does (Promised group + Personal group, one chat)
    "pulse": "Pulse",  # LIFECYCLE1 — RETIRED taskId (out of DEFAULT_SCHEDULES; row kept forever so pre-retirement receipts and any still-registered task render with a name, never a bare id)
    "past-meetings": "Past Meetings",  # EOD2 — RENAMED taskId (out of DEFAULT_SCHEDULES; row kept FOREVER so pre-rename receipts and any still-registered task render with a name, never a bare id). Its `pack_run` receipts are the SAME series `end-of-day` continues — see end_of_day.TASK_ID.
    "end-of-day": "End of Day",  # EOD2 — the 5 PM close; successor id of `past-meetings` (same orchestrator file, same pack, same receipt series)
    "friday-wrap": "Friday Wrap",  # v3.11.0
    "cleanup": "Cleanup",  # v3.17.0 — silent weekly self-maintenance (not a CEO-facing chat)
    "reconcile-sent": "Reconcile Sent",  # v3.18.12 — silent daily sent-mail reconciliation (not a CEO-facing chat)
    "relationship-moves": "Relationship Moves",  # REL1 — weekly Sunday outreach action pack
    "commitment-triage": "Commitment Triage",  # TASKRET1 — READINESS-RETIRED taskId (out of DEFAULT_SCHEDULES; row kept forever so pre-retirement receipts and any still-registered task render with a name, never a bare id). The on-demand skill of the same name is untouched.
    "monthly-report": "Monthly Report",  # C1 — silent monthly operator-report + value-receipt fire (not a CEO-facing chat)
    "weekly-insights": "Weekly Insights",  # v4.2.0 — silent weekly analytical-view synthesis (not a CEO-facing chat); a maintenance JOB as of MAINT1
    "session-sweep": "Session Sweep",  # Phase 5 / R1 — silent nightly transcript-to-event promotion (not a CEO-facing chat); a maintenance JOB as of MAINT1
    "maintenance": "Maintenance",  # MAINT1 — THE silent background dispatcher task (not a CEO-facing chat). cleanup / reconcile-sent / monthly-report keep their rows above for job-level renders.
    "staff-meeting": "Staff Meeting",  # LB1 R3 — weekly Monday Living Brain review chat (opt-in later-add)
    "balance": "Balance",  # TASKRET1 — READINESS-RETIRED taskId (out of DEFAULT_SCHEDULES; row kept forever for legacy renders). The on-demand `balance check` surface is untouched.
    # TASKRET1 — pipeline-digest had NO row here before it was retired, and
    # `retirement_line` reads THIS dict rather than `task_display_name`, so it
    # would have rendered the bare taskId into a customer sentence ("Your
    # pipeline-digest chat is off the schedule"). Every RETIRED_TASKS id needs
    # a row here for exactly that reason; a test pins the invariant so the next
    # retirement cannot reintroduce it.
    "pipeline-digest": "Pipeline Digest",  # PIPE1 Part 2 → TASKRET1 READINESS-RETIRED taskId (row kept forever for legacy renders). The on-demand pipeline report is untouched.
    "deal-signals": "Deal Signals",  # LB1 D7 — silent deal-signal detector (a maintenance JOB, not a task; row kept for job-level renders)
    "review-expiry": "Unconfirmed Cleanup",  # REVSCHED1 §3-2 — silent weekly unconfirmed-pile drain (a maintenance JOB, not a task; row exists so the watchdog's job-level line reads as English and never as a bare id)
}


# -----------------------------------------------------------------------------
# Cron parsing + human-readable rendering
# -----------------------------------------------------------------------------


_DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
_DAY_ABBREVS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
_MONTH_NAMES = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]


class CronParseError(ValueError):
    """Raised when a cron expression doesn't parse."""


def _parse_field(field: str, lo: int, hi: int) -> set[int]:
    """Parse a single cron field into the set of integer values it covers.

    Supports: `*`, `N`, `N-M`, `N,M,K`, `*/N`, `N-M/K`. Raises CronParseError
    on anything malformed.
    """
    if field == "*":
        return set(range(lo, hi + 1))

    out: set[int] = set()
    for chunk in field.split(","):
        chunk = chunk.strip()
        if not chunk:
            raise CronParseError(f"empty field segment in {field!r}")

        step = 1
        if "/" in chunk:
            base, step_str = chunk.split("/", 1)
            try:
                step = int(step_str)
            except ValueError:
                raise CronParseError(f"non-int step in {chunk!r}")
            if step < 1:
                raise CronParseError(f"step must be >= 1, got {step}")
            chunk = base.strip() or "*"

        if chunk == "*":
            out.update(range(lo, hi + 1, step))
        elif "-" in chunk:
            try:
                a, b = chunk.split("-", 1)
                a_val, b_val = int(a), int(b)
            except ValueError:
                raise CronParseError(f"bad range in {chunk!r}")
            if a_val > b_val:
                raise CronParseError(f"range start > end in {chunk!r}")
            out.update(range(a_val, b_val + 1, step))
        else:
            try:
                out.add(int(chunk))
            except ValueError:
                raise CronParseError(f"non-int field {chunk!r}")

    bad = [v for v in out if v < lo or v > hi]
    if bad:
        raise CronParseError(f"value(s) {bad} out of range [{lo},{hi}] in {field!r}")
    return out


def parse_cron(expr: str) -> tuple[set[int], set[int], set[int], set[int], set[int]]:
    """Parse a 5-field cron expression. Returns the five field sets.

    Raises CronParseError if expression is malformed.
    """
    if not expr or not isinstance(expr, str):
        raise CronParseError("cron expression must be non-empty string")
    parts = expr.strip().split()
    if len(parts) != 5:
        raise CronParseError(
            f"expected 5 fields (minute hour dom month dow), got {len(parts)}: {expr!r}"
        )
    minute = _parse_field(parts[0], 0, 59)
    hour = _parse_field(parts[1], 0, 23)
    dom = _parse_field(parts[2], 1, 31)
    month = _parse_field(parts[3], 1, 12)
    dow = _parse_field(parts[4], 0, 6)
    return minute, hour, dom, month, dow


def cron_to_english(expr: str) -> str:
    """Render a cron expression as a plain-English label.

    Best-effort — covers the common scheduled-task patterns. Falls back to
    raw cron if pattern is too complex to summarize cleanly.

    Examples:
        "0 7 * * 1-5"      → "7 AM weekdays"
        "30 8 * * 1-5"     → "8:30 AM weekdays"
        "0 7,15 * * 1-5"   → "7 AM and 3 PM weekdays"
        "0 9 * * 1"        → "9 AM Mondays"
        "0 9 * * *"        → "9 AM daily"
        "0 */2 * * 1-5"    → "every 2 hours weekdays"
    """
    try:
        minute_set, hour_set, dom_set, month_set, dow_set = parse_cron(expr)
    except CronParseError:
        return expr  # fall back to raw

    parts = expr.strip().split()
    minute_field, hour_field, dom_field, month_field, dow_field = parts

    # Step expressions ("*/N") get a special-case rendering
    if "/" in hour_field and minute_field == "0" and len(hour_set) > 1:
        try:
            step = int(hour_field.split("/", 1)[1])
        except ValueError:
            step = 1
        time_str = f"every {step} hours" if step > 1 else "hourly"
    else:
        # Simple time render: pick first hour + minute (most cron schedules are
        # single-time or short list)
        if len(hour_set) == 1:
            h = next(iter(hour_set))
            m = next(iter(minute_set)) if len(minute_set) == 1 else 0
            time_str = _format_time(h, m)
        elif len(hour_set) <= 4 and len(minute_set) == 1:
            m = next(iter(minute_set))
            times = [_format_time(h, m) for h in sorted(hour_set)]
            if len(times) == 2:
                time_str = f"{times[0]} and {times[1]}"
            else:
                time_str = ", ".join(times[:-1]) + f", and {times[-1]}"
        else:
            return expr  # too complex; raw cron

    # Day-of-week / day-of-month qualifier
    day_str = _format_day_qualifier(dow_field, dom_field, dow_set, dom_set)

    if day_str:
        return f"{time_str} {day_str}"
    return time_str


def _format_time(hour: int, minute: int) -> str:
    """Format hour+minute as e.g. "7 AM" / "8:30 AM" / "5 PM" / "12:15 PM"."""
    period = "AM" if hour < 12 else "PM"
    h12 = hour % 12 or 12
    if minute == 0:
        return f"{h12} {period}"
    return f"{h12}:{minute:02d} {period}"


def _format_day_qualifier(
    dow_field: str, dom_field: str, dow_set: set[int], dom_set: set[int]
) -> str:
    """Render the day-of-week / day-of-month qualifier as English."""
    # Most common case: dom is "*" and dow is the qualifier
    if dom_field == "*":
        if dow_field == "*":
            return "daily"
        if dow_set == {1, 2, 3, 4, 5}:
            return "weekdays"
        if dow_set == {0, 6}:
            return "weekends"
        if len(dow_set) == 1:
            d = next(iter(dow_set))
            return f"{_DAY_NAMES[d]}s"  # "Mondays", "Fridays"
        if len(dow_set) <= 4:
            names = [_DAY_ABBREVS[d] for d in sorted(dow_set)]
            return ", ".join(names)
        # Too many days, just say "X days/week"
        return f"{len(dow_set)} days/week"

    # dom-restricted (e.g., "1st of month") — less common in our use case
    if dow_field == "*" and len(dom_set) == 1:
        d = next(iter(dom_set))
        suffix = _ordinal_suffix(d)
        return f"on the {d}{suffix} of each month"

    return ""


def _ordinal_suffix(n: int) -> str:
    if 10 <= n % 100 <= 20:
        return "th"
    return {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")


# -----------------------------------------------------------------------------
# Storage helpers — read + merge defaults
# -----------------------------------------------------------------------------


def load_schedule_config(entities_json_path: str | Path) -> dict[str, dict]:
    """Read the workspace schedule config from entities.json. Returns a dict
    mapping taskId → {cron, label, enabled} for ALL known tasks (config values
    if set, defaults otherwise). Missing or unreadable entities.json returns
    full defaults.

    Tasks not in DEFAULT_SCHEDULES are NOT included — caller is responsible
    for tasks they introduce post v2.14.10.

    **A RENAMED predecessor's override is INHERITED (EOD2 / REVIEW F-1).** The
    override store is keyed by taskId, and a renamed predecessor's key is no
    longer a DEFAULT_SCHEDULES key — so without this the customer's own hour
    is silently dropped from the merged view, and `schedule_task_id` then
    resolves the predecessor to the successor's SHIPPED DEFAULT. A workspace
    customised to 4 PM that has not taken the rename would be scored against
    the 5 PM default: ~23 hours "late" on every evening fire, a false
    catch-up banner, and `change-schedule` rendering "5 PM weekdays" for a
    chat that fires at 4. Silent, because the orphan-override scan skips a
    key whose id is still registered.

    D-3 carried the ID across the rename; this carries the OVERRIDE KEY, and
    it is the same defect one layer down. The successor's OWN override always
    wins — this only fills a gap, and it is the read-side mirror of the "move
    the override" instruction `change-schedule` already gives the accept path.
    The whole override dict travels (cron, label AND enabled), because a
    customer who PAUSED the old id has equally not asked for it to come back.
    """
    config_overrides = {}
    path = Path(entities_json_path)
    if path.exists():
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            workspace = data.get("workspace") or {}
            config_overrides = workspace.get("schedule_config") or {}
        except (json.JSONDecodeError, OSError):
            # Corrupted or unreadable — use defaults
            config_overrides = {}

    merged = {}
    for task_id, default in DEFAULT_SCHEDULES.items():
        override = config_overrides.get(task_id) or {}
        if not override:
            for pred in renamed_predecessors(task_id):
                inherited = config_overrides.get(pred) or {}
                if inherited:
                    override = inherited
                    break
        merged[task_id] = {
            "cron": override.get("cron", default["cron"]),
            "label": override.get("label") or cron_to_english(
                override.get("cron", default["cron"])
            ),
            "enabled": (
                override["enabled"] if "enabled" in override else default["enabled"]
            ),
        }
    return merged


def later_add_task_ids() -> frozenset:
    """Default tasks that are deliberately NOT first-install — they need
    accumulated workspace signal before they fire well, and register via the
    existing later-add paths (change-schedule Phase 6 `add` / update-bridge).

    DERIVED, never duplicated: a DEFAULT_SCHEDULES entry outside
    FIRST_INSTALL_TASK_IDS is a later-add by definition. A default entry
    does NOT imply registration — that's the R1 ghost-task lesson
    (relationship-moves rendered as an enabled Sunday task on workspaces
    where it was never added).

    A RETIRED task can never appear here, in any class: retirement takes the
    row OUT of DEFAULT_SCHEDULES, and "not yet added" is the one thing a
    retired surface is not. TASKRET1 is the case that made the distinction
    load-bearing — `commitment-triage`, `pipeline-digest` and `balance` were
    all later-adds the week before, so every surface that treats this set as
    "things worth offering" stops offering them for free.
    """
    return frozenset(DEFAULT_SCHEDULES) - FIRST_INSTALL_TASK_IDS


def registration_target_set(existing_registered) -> frozenset[str]:
    """The set an EXISTING workspace's registration re-run may register
    (`enable-command-room-schedules` Phase 3's non-first-install branch).

    The union `existing | FIRST_INSTALL_TASK_IDS` is what makes a pre-M1
    customer pick up `inbox` on their next re-run without losing anything
    they already have. EOD2 puts one fence around it, and the fence is the
    whole propose-never-auto-apply posture in code:

    **A first-install task whose RENAMED PREDECESSOR is still registered here
    is REMOVED from the target set.** Without it, `end-of-day` — a first-
    install id from the moment EOD2 ships — would auto-register on the next
    registration run of every workspace in the fleet, silently handing each
    customer a SECOND 5 PM chat beside the `past-meetings` one they can see
    in their Scheduled list. That is the add-without-asking violation with a
    new name on it, and it is exactly what M's Decision 9 forbids.

    The rename reaches a workspace one way only: the customer takes the offer
    (`schedule_proposals.propose_task_retirements` →
    `retirement_line("past-meetings")` → `add end of day`). Then the id IS in
    `existing` and this function stops fencing it.

    A retired id already in `existing` stays in the target set on purpose —
    that is what keeps its registered prompt refreshed, and for a RENAMED id
    it is what keeps the old task firing the real pack. A retired id that is
    NOT registered can never enter: retired ids are never in
    FIRST_INSTALL_TASK_IDS.
    """
    existing = frozenset(existing_registered or ())
    target = set(existing | FIRST_INSTALL_TASK_IDS)
    for task_id in FIRST_INSTALL_TASK_IDS - existing:
        if any(pred in existing for pred in renamed_predecessors(task_id)):
            target.discard(task_id)
    return frozenset(target)


def load_schedule_view(
    entities_json_path: str | Path,
    registered_ids,
) -> dict[str, dict]:
    """The registration-aware schedule view (Phase 3 / corrected R1).

    `load_schedule_config` merges defaults + overrides but knows nothing
    about what is actually registered in Cowork's scheduler — so later-add
    tasks rendered as live scheduled tasks on workspaces where they were
    never added (the relationship-moves ghost). This wrapper partitions the
    merged view against the registered-task set.

    Args:
      registered_ids: the registered taskId set. The maintained offline-first
        record is `_hq/workspace_config.json` `registered_taskIds` (written
        by enable-command-room-schedules Phase 0.C and kept current through
        its Phase 3 / Phase 6 flows); pass taskIds from
        `mcp__scheduled-tasks__list_scheduled_tasks` instead when the caller
        has them (fresher). Pass an empty set if neither exists — everything
        then renders as available/not-added, which is the honest answer.

    Returns {task_id: {cron, label, enabled, registered: bool,
    later_add: bool, silent: bool, served_by: str|None}}. NO task should be
    rendered as a live scheduled task unless `registered` is True.

    `registered` is TRUE for a task served by a renamed predecessor (EOD2):
    a workspace running `past-meetings` HAS its evening close, and rendering
    `end-of-day` under "Available, not added yet" would invite the customer
    to register a second 5 PM chat. `served_by` names that predecessor when
    it is what the machine actually has, and is None otherwise — renders use
    it to say "registered as Past Meetings" instead of claiming a taskId the
    Scheduled list does not show.
    """
    registered = set(registered_ids or ())
    later = later_add_task_ids()
    view = {}
    for task_id, spec in load_schedule_config(entities_json_path).items():
        own = task_id in registered
        served_by = None
        if not own:
            for pred in renamed_predecessors(task_id):
                if pred in registered:
                    served_by = pred
                    break
        view[task_id] = {
            **spec,
            "registered": own or served_by is not None,
            "later_add": task_id in later,
            "silent": task_id in SILENT_TASKS,
            "served_by": served_by,
        }
    return view


def workspace_time_to_machine(
    hour: int,
    minute: int,
    workspace_root,
) -> tuple[int, int]:
    """Convert a user-requested wall-clock time (workspace TZ — what the
    user MEANS by "8am") to the machine-local time cron must carry (R8:
    cron/fireAt evaluate in MACHINE-local time; workspace TZ is
    presentation-only).

    Uses the CURRENT offset between the two zones (a fixed cron can't track
    DST transitions — when the offset shifts, the fire drifts by the DST
    hour until re-registered; same limitation any fixed cron has). Falls
    back to the unconverted time when the workspace TZ can't resolve —
    machine == workspace is the common case.
    """
    import datetime as _dt2

    try:
        from tz import load_workspace_tz

        ws_tz = load_workspace_tz(workspace_path=workspace_root)
        now_machine = _dt2.datetime.now().astimezone()
        # The instant at which the workspace-TZ wall clock reads hour:minute today:
        ws_now = now_machine.astimezone(ws_tz)
        ws_target = ws_now.replace(hour=hour, minute=minute, second=0, microsecond=0)
        machine_target = ws_target.astimezone(now_machine.tzinfo)
        return machine_target.hour, machine_target.minute
    except Exception:
        return hour, minute


def task_display_name(task_id: str) -> str:
    """Map taskId → user-facing display name. Falls back to taskId stripped
    of the `cr-` prefix if not in DISPLAY_NAMES.
    """
    if task_id in DISPLAY_NAMES:
        return DISPLAY_NAMES[task_id]
    return task_id.removeprefix("cr-").replace("-", " ").title()


SCHEDULE_CONFIG_CHANGED = "schedule_config_changed"


def log_schedule_config_change(workspace_root, changes, *,
                               source_skill: str,
                               extra_data: dict | None = None) -> dict | None:
    """THE writer for `schedule_config_changed`. Returns the event, or None.

    THE FINDING (SPEC SCHED1 §0-4, 2026-08-17). Every path that ENABLES,
    DISABLES or PAUSES a scheduled task has to leave a record, because the
    lateness ledger reads that record: `served_slot_markers` treats a slot
    older than the newest `schedule_config_changed` as retroactively minted by
    the change and never scores it (the F-51 phantom). `change-schedule` writes
    one. The registration flow's own pause paths did not — the 2026-08-17
    fold-in wrote three `schedule_created` events and NO record for the two
    chats it paused, so from the ledger's side those pauses never happened and
    the newest config change on file was a week old.

    WHY A HELPER AND NOT A PARAGRAPH PER SITE. There are five prose sites that
    pause or disable a task across two skills, and a mandate repeated five
    times is a mandate presumed skipped (the Bug #98 class this repo keeps
    re-learning). One call, one shape, one place to fix.

    `changes` is an iterable of dicts or `(task_id, cron, enabled)` tuples;
    every row is normalized to `{task_id, cron, enabled}` so the read side —
    which already accepts both the list shape and the flat single-task shape —
    only ever meets one of them from new writers. The task id is normalized
    for SPELLING only: a renamed predecessor keeps its own name here, because
    this is a record of what the customer did, not a question about cadence.

    `extra_data` (TASKRET1 main-merge, 2026-08-17) lets a caller annotate WHY
    the change happened — the readiness-retirement migration rides its
    `migration_id` here, and the bridge's adjudication gate suppresses on that
    id. It exists so a pause path with something extra to say still routes THIS
    writer instead of hand-rolling an event beside it: a second writer is how
    the shape drifts, and the whole point of this function is that
    `served_slot_markers` can read back everything that claims to be a config
    change. Annotations ride ALONGSIDE `changes` and can never replace it —
    the row shape is the contract, not the caller's to redefine.

    Best-effort by design: a registration that succeeded must not be reported
    as failed because its audit event could not be appended (RELIABILITY.md).
    Returns None when there is nothing to record or the append failed.
    """
    # SPELLING normalization only, never rename RESOLUTION. `schedule_task_id`
    # answers "whose cron governs this?" and maps a renamed predecessor onto
    # its successor — correct for cadence, a falsehood in an audit record: a
    # customer who paused `past-meetings` did not pause `end-of-day`, and the
    # ledger's reader already folds predecessors in on the READ side.
    try:
        from receipts import normalize_task_id as _norm
    except Exception:  # noqa: BLE001
        def _norm(value):
            return value

    rows = []
    try:
        iter(changes)
    except TypeError:
        return None
    for change in changes or []:
        if isinstance(change, dict):
            task_id = change.get("task_id") or change.get("taskId")
            cron = change.get("cron")
            enabled = change.get("enabled")
        elif isinstance(change, (list, tuple)) and len(change) == 3:
            task_id, cron, enabled = change
        else:
            continue
        if not isinstance(task_id, str) or not task_id.strip():
            continue
        rows.append({
            "task_id": _norm(task_id.strip()) or task_id.strip(),
            "cron": cron if isinstance(cron, str) and cron.strip() else None,
            "enabled": bool(enabled) if enabled is not None else None,
        })
    if not rows:
        return None

    data: dict = {"changes": rows}
    # `setdefault`, not `update`: an annotation never overwrites `changes`, and
    # never overwrites a field this writer already owns. A caller that wants a
    # different row shape wants a different event type.
    for key, value in (extra_data or {}).items():
        if isinstance(key, str) and key.strip():
            data.setdefault(key, value)

    event = {
        "type": SCHEDULE_CONFIG_CHANGED,
        "source_skill": str(source_skill or "").strip() or "change-schedule",
        "data": data,
    }
    try:
        import sys as _sys
        _here = str(Path(__file__).resolve().parent)
        if _here not in _sys.path:
            _sys.path.insert(0, _here)
        from event_gate import append_event

        events_path = Path(workspace_root) / "_hq" / "data" / "events.jsonl"
        events_path.parent.mkdir(parents=True, exist_ok=True)
        append_event(events_path, event, holder=f"schedule:{event['source_skill']}")
        return event
    except Exception:  # noqa: BLE001 — the audit event never blocks the change
        return None


def rm_supersede_plan(registered_tasks: list) -> dict | None:
    """LB2 §3d — the `rm_supersede_v1` planner (pure; the update bridge
    executes it, adjudication-gated, on the user's explicit yes — NEVER
    silently).

    LB1 R4 left workspaces that already registered a standalone
    relationship-moves chat in a permanent fork: R4's own suppression rule
    means they are never offered the staff meeting, so the moves never merge
    into the one adjudication surface. This plans the fold: given the LIVE
    registered task records (from the scheduler MCP — each carries at least
    `taskId` and `cron`), returns None when no standalone relationship-moves
    registration exists (nothing to supersede — most workspaces), else:

        {"marker": "rm_supersede_v1",
         "remove_task_id": "relationship-moves",
         "staff_meeting_registered": bool,   # already there → register step skipped
         "carry_cron": str | None}           # the RM chat's CUSTOM cron, to
                                             # carry onto a NEW staff-meeting
                                             # registration; None = RM was on
                                             # its default → use the
                                             # staff-meeting default (M/W/F)

    Decline path and idempotency are the bridge's adjudication machinery
    (`migration_adjudication` on the marker id) — this planner holds no
    state. The RM skill, its orchestrator, and Pulse are untouched by design.
    """
    rm = None
    sm_registered = False
    for t in registered_tasks or []:
        if not isinstance(t, dict):
            continue
        tid = t.get("taskId") or t.get("task_id") or t.get("id")
        if tid == "relationship-moves":
            rm = t
        elif tid == "staff-meeting":
            sm_registered = True
    if rm is None:
        return None
    rm_default = DEFAULT_SCHEDULES.get("relationship-moves", {}).get("cron")
    rm_cron = (rm.get("cron") or "").strip()
    carry = rm_cron if (rm_cron and rm_cron != rm_default) else None
    return {
        "marker": "rm_supersede_v1",
        "remove_task_id": "relationship-moves",
        "staff_meeting_registered": sm_registered,
        "carry_cron": carry,
    }


__all__ = [
    "rm_supersede_plan",
    "DEFAULT_SCHEDULES",
    "FIRST_INSTALL_TASK_IDS",
    "SILENT_TASKS",
    "SUPERSEDED_BY",
    "RETIRED_TASKS",
    "RETIRE_SUPPRESSION_WEEKS",
    "is_retired_task",
    "is_renamed_task",
    "RETIREMENT_CLASS_ELIMINATION",
    "RETIREMENT_CLASS_RENAME",
    "RETIREMENT_CLASS_READINESS",
    "retirement_class",
    "is_readiness_retirement",
    "readiness_retired_task_ids",
    "reoffer_condition",
    "readiness_retirement_summary",
    "renamed_predecessors",
    "schedule_task_id",
    "serving_task_ids",
    "is_task_served",
    "cron_time_phrase",
    "retirement_reason",
    "retirement_line",
    "is_silent_task",
    "compose_silent_task_prompt",
    "later_add_task_ids",
    "registration_target_set",
    "load_schedule_view",
    "workspace_time_to_machine",
    "DISPLAY_NAMES",
    "CronParseError",
    "parse_cron",
    "cron_to_english",
    "load_schedule_config",
    "task_display_name",
    "SCHEDULE_CONFIG_CHANGED",
    "log_schedule_config_change",
]
